apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-crawler"},"name":"synergychat-crawler","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-crawler"}},"template":{"metadata":{"labels":{"app":"synergychat-crawler"}},"spec":{"containers":[{"env":[{"name":"CRAWLER_PORT","valueFrom":{"configMapKeyRef":{"key":"CRAWLER_PORT","name":"synergychat-crawler-configmap"}}},{"name":"CRAWLER_KEYWORDS","valueFrom":{"configMapKeyRef":{"key":"CRAWLER_KEYWORDS","name":"synergychat-crawler-configmap"}}}],"image":"docker.io/bootdotdev/synergychat-crawler:latest","name":"synergychat-crawler"}]}}}}
  creationTimestamp: "2025-05-29T17:13:58Z"
  generation: 2
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
  namespace: default
  resourceVersion: "117784"
  uid: ddf02f6f-4852-4399-9418-c315769109f5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-crawler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - name: synergychat-crawler-1
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              key: CRAWLER_PORT
              name: synergychat-crawler-configmap
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              key: CRAWLER_KEYWORDS
              name: synergychat-crawler-configmap
        image: docker.io/bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /cache
            name: cache-volume

      - name: synergychat-crawler-2
        image: docker.io/bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /cache
            name: cache-volume
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_PORT_2
                name: synergychat-crawler-configmap

          - name: CRAWLER_KEYWORDS
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_KEYWORDS
                name: synergychat-crawler-configmap

          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap


      - name: synergychat-crawler-3
        image: docker.io/bootdotdev/synergychat-crawler:latest
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /cache
            name: cache-volume
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_PORT_3
                name: synergychat-crawler-configmap

          - name: CRAWLER_KEYWORDS
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_KEYWORDS
                name: synergychat-crawler-configmap

          - name: CRAWLER_DB_PATH
            valueFrom:
              configMapKeyRef:
                key: CRAWLER_DB_PATH
                name: synergychat-crawler-configmap



        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
        - name: cache-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-29T17:13:58Z"
    lastUpdateTime: "2025-05-29T17:23:27Z"
    message: ReplicaSet "synergychat-crawler-67ffc7cd59" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T22:29:24Z"
    lastUpdateTime: "2025-06-01T22:29:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
