apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"synergychat-api"},"name":"synergychat-api","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"synergychat-api"}},"template":{"metadata":{"labels":{"app":"synergychat-api"}},"spec":{"containers":[{"env":[{"name":"API_PORT","valueFrom":{"configMapKeyRef":{"key":"API_PORT","name":"synergychat-api-configmap"}}}],"image":"docker.io/bootdotdev/synergychat-api:latest","name":"synergychat-api"}]}}}}
  creationTimestamp: "2025-05-28T23:40:55Z"
  generation: 1
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: default
  resourceVersion: "117794"
  uid: 72377daf-0ea1-44e0-b260-8788fa0e6791
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-api
    spec:
      containers:
        - name: synergychat-api
          image: docker.io/bootdotdev/synergychat-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: synergychat-api-configmap
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-28T23:40:55Z"
    lastUpdateTime: "2025-05-28T23:41:29Z"
    message: ReplicaSet "synergychat-api-54dd45c986" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-01T22:29:25Z"
    lastUpdateTime: "2025-06-01T22:29:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
