# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  01:setup-minikube: 
    cmds:
      - minikube start --extra-config "apiserver.cors-allowed-origins=["http://boot.dev"]"
      - minikube dashboard --port=63840
