apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    kind: Deployment
    name: synergychat-web
