apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-06-03T10:56:37Z","generation":1,"labels":{"app":"synergychat-testcpu"},"name":"synergychat-testcpu","namespace":"default","resourceVersion":"165044","uid":"14e80fa0-02b1-455a-9683-5d8c1021308c"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"synergychat-testcpu"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"synergychat-testcpu"}},"spec":{"containers":[{"image":"bootdotdev/synergychat-testcpu:latest","imagePullPolicy":"Always","name":"synergychat-testcpu","resources":{"limits":{"cpu":"50m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-06-03T10:56:43Z","lastUpdateTime":"2025-06-03T10:56:43Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-06-03T10:56:37Z","lastUpdateTime":"2025-06-03T10:56:43Z","message":"ReplicaSet \"synergychat-testcpu-6f49786bf7\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-06-03T10:56:37Z"
  generation: 4
  labels:
    app: synergychat-testcpu
  name: synergychat-testcpu
  namespace: default
  resourceVersion: "188502"
  uid: 14e80fa0-02b1-455a-9683-5d8c1021308c
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: synergychat-testcpu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: synergychat-testcpu
    spec:
      containers:
      - image: bootdotdev/synergychat-testcpu:latest
        imagePullPolicy: Always
        name: synergychat-testcpu
        resources:
          limits:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-06-03T12:09:20Z"
    lastUpdateTime: "2025-06-03T12:09:37Z"
    message: ReplicaSet "synergychat-testcpu-948d9c798" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-04T18:02:34Z"
    lastUpdateTime: "2025-06-04T18:02:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
