apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBjCCAe6gAwIBAgIBATANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
      a3ViZUNBMB4XDTI1MDUyNDE1NTkyMVoXDTM1MDUyMzE1NTkyMVowFTETMBEGA1UE
      AxMKbWluaWt1YmVDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPBj
      kPmjhsqWnmG1d1IVpRkIYOWw94pddTFZlmszSXWf7Dnj+pL3ur8A41w3a4jgVumE
      y9kIYy4iGiVfQdSQfYfavovajDtbohZjS9M61EwdmLFkQBekgKHr+E6Dwy6tg2K+
      1BXoET89PkhT+0m+IU+dl14AvxiyqeP72AwmWKuTxyBLdWWdDDk3hRZ1oNfvdZZf
      2On7QXrUvTbdiLlm6AzLzLwmkeMXZh1rcf6cg7vSSHFa2I2JILM4UN88augK3R9Y
      yzFqd4nEL4uvA9/t5QX6gKvJ/RdAfFt8uNZqfjsAzhQ3LKmZPvaujps+Sg8KctUh
      U9efQCmRHfOh2X85Lx0CAwEAAaNhMF8wDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQW
      MBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
      BBQYN/2Qa5MWX85Q+8y9AFUUEQBgazANBgkqhkiG9w0BAQsFAAOCAQEALqeCkv+0
      lLtBoOeXLSVVee0mEu9dB0dsFi82H2RJ8vRV9xrW5UEYDNs7Xm4TcaQNN6euED7x
      sqN6i4LP7hdZ2N45CkUmuWH1gZGeTOyol4KTlW8sPEtcG8XPPMSEKKNR9iLRzr2b
      ISiMZAgkCvNAGWgev0vE/tSyCPsQvBGdi9wZwGWx6m3kmkqF/imaD+GGQsJdYJjW
      rFap6aY0hDCXJDriUhPFWDyr/vfiAwLLftOKTe3pJNChxWRsMX47RXTelWy7/F0+
      1IhM3pJgq6HTUK7hkeuf13QnvVOW9gcMjc2gDf5RRnRa+DIaPkJkmwc5TU0AMJ5P
      uUsIHgZ7i5abQg==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-06-03T01:29:17Z"
    name: kube-root-ca.crt
    namespace: crawler
    resourceVersion: "158488"
    uid: a49ccf41-010e-44ba-bad1-088a1c97241b
- apiVersion: v1
  data:
    CRAWLER_DB_PATH: /cache/db
    CRAWLER_KEYWORDS: gutenberg books
    CRAWLER_PORT: "8080"
    CRAWLER_PORT_2: "8081"
    CRAWLER_PORT_3: "8082"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"CRAWLER_DB_PATH":"/cache/db","CRAWLER_KEYWORDS":"gutenberg books","CRAWLER_PORT":"8080","CRAWLER_PORT_2":"8081","CRAWLER_PORT_3":"8082"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-05-29T17:09:49Z","name":"synergychat-crawler-configmap","namespace":"crawler","resourceVersion":"130220","uid":"9869bee5-b367-46d8-bd03-acd6d0b5e22b"}}
    creationTimestamp: "2025-06-03T01:37:14Z"
    name: synergychat-crawler-configmap
    namespace: crawler
    resourceVersion: "158935"
    uid: 08ef5e9f-bdfc-4edf-ab5a-620c340ab688
kind: List
metadata:
  resourceVersion: ""
