apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2025-05-30T11:56:04Z","name":"crawler-service","namespace":"crawler","resourceVersion":"47583","uid":"125e8fde-9dfd-45ea-9413-02dd53d6bc8a"},"spec":{"clusterIP":"10.103.71.81","clusterIPs":["10.103.71.81"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"synergychat-crawler"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2025-06-03T01:41:01Z"
    name: crawler-service
    namespace: crawler
    resourceVersion: "159198"
    uid: b5e353e2-5a4b-43db-a586-f7cc2fc05350
  spec:
    clusterIP: 10.103.71.81
    clusterIPs:
    - 10.103.71.81
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: synergychat-crawler
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
