apiVersion: v1
data:
  CRAWLER_DB_PATH: /cache/db
  CRAWLER_KEYWORDS: gutenberg books
  CRAWLER_PORT: "8080"
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CRAWLER_DB_PATH":"/cache/db","CRAWLER_KEYWORDS":"gutenberg books","CRAWLER_PORT":"8080","CRAWLER_PORT_2":"8081","CRAWLER_PORT_3":"8082"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-05-29T17:09:49Z","name":"synergychat-crawler-configmap","namespace":"default","resourceVersion":"36406","uid":"9869bee5-b367-46d8-bd03-acd6d0b5e22b"}}
  creationTimestamp: "2025-05-29T17:09:49Z"
  name: synergychat-crawler-configmap
  namespace: crawler
  resourceVersion: "130220"
  uid: 9869bee5-b367-46d8-bd03-acd6d0b5e22b
